package kp.company.endpoints;

import kp.company.TestDatasetLoader;
import kp.company.domain.Employee;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.hateoas.MediaTypes;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.ResultActions;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;

import java.lang.invoke.MethodHandles;

import static kp.Constants.EMPLOYEES_PATH;
import static kp.TestConstants.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * The tests for the {@link Employee} with server-side support using {@link MockMvc}.
 * <p>
 * The endpoints were generated by Spring Data from the repositories.
 * </p>
 */
@SpringBootTest
@AutoConfigureMockMvc
class EmployeeEndpointsTests {
    private static final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private TestDatasetLoader testDatasetLoader;

    private static final boolean VERBOSE = false;

    /**
     * Should create the {@link Employee}.
     * <p>
     * Tests a <b>POST</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldCreateEmployee() throws Exception {
        // GIVEN
        final MockHttpServletRequestBuilder requestBuilder = post(EMPLOYEES_URL).accept(MediaTypes.HAL_JSON_VALUE)
                .content(CREATED_EMPLOYEE_CONTENT).contentType(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isCreated());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        resultActions.andExpect(jsonPath("firstName").value(CREATED_EMPLOYEE_F_NAME));
        resultActions.andExpect(jsonPath("lastName").value(CREATED_EMPLOYEE_L_NAME));
        resultActions.andExpect(jsonPath("_links.self.href").value(CREATED_EMPLOYEE_ID_HREF));
        resultActions.andExpect(jsonPath("_links.employee.href").value(CREATED_EMPLOYEE_ID_HREF));
        resultActions.andExpect(jsonPath("_links.department.href").value(CREATED_EMPLOYEE_ID_DEP_HREF));
        logger.info("shouldCreateEmployee():");
    }

    /**
     * Should update the {@link Employee}.
     * <p>
     * Tests a <b>PATCH</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldUpdateEmployeeUsingPatch() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = patch(EXPECTED_EMPLOYEE_ID_URL)
                .accept(MediaTypes.HAL_JSON_VALUE).content(UPDATED_EMPLOYEE_CONTENT)
                .contentType(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        checkEmployee(resultActions, UPDATED_EMPLOYEE_F_NAME, UPDATED_EMPLOYEE_L_NAME);
        logger.info("shouldUpdateEmployeeUsingPatch():");
    }

    /**
     * Should update the {@link Employee}.
     * <p>
     * Tests a <b>PUT</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldUpdateEmployeeUsingPut() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = put(EXPECTED_EMPLOYEE_ID_URL)
                .accept(MediaTypes.HAL_JSON_VALUE).content(UPDATED_EMPLOYEE_CONTENT)
                .contentType(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        checkEmployee(resultActions, UPDATED_EMPLOYEE_F_NAME, UPDATED_EMPLOYEE_L_NAME);
        logger.info("shouldUpdateEmployeeUsingPut():");
    }

    /**
     * Should get '404 Not Found' error response when updating the absent {@link Employee}.
     * <p>
     * Tests a <b>PATCH</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldGetNotFoundErrorOnUpdateWithAbsentEmployee() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final String urlTemplate = "%s%s/%d".formatted(ROOT_URL, EMPLOYEES_PATH, ABSENT_EMPLOYEE_ID);
        final MockHttpServletRequestBuilder requestBuilder = patch(urlTemplate).accept(MediaTypes.HAL_JSON_VALUE)
                .content(UPDATED_EMPLOYEE_CONTENT).contentType(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isNotFound());
        logger.info("shouldGetNotFoundErrorOnUpdateWithAbsentEmployee():");
    }

    /**
     * Should delete the {@link Employee}.
     * <p>
     * Tests a <b>DELETE</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldDeleteEmployee() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = delete(EXPECTED_EMPLOYEE_ID_URL)
                .accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        logger.info("shouldDeleteEmployee():");
    }

    /**
     * Should find the {@link Employee} by id.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldFindEmployeeById() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = get(EXPECTED_EMPLOYEE_ID_URL)
                .accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        checkEmployee(resultActions, EXPECTED_EMPLOYEE_F_NAME, EXPECTED_EMPLOYEE_L_NAME);
        logger.info("shouldFindEmployeeById():");
    }

    /**
     * Should get '404 Not Found' error response when searching with the absent employee's id.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldGetNotFoundErrorOnSearchWithAbsentEmployee() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final String urlTemplate = "%s/99999".formatted(EMPLOYEES_URL);
        final MockHttpServletRequestBuilder requestBuilder = get(urlTemplate).accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isNotFound());
        logger.info("shouldGetNotFoundErrorOnSearchWithAbsentEmployee():");
    }

    /**
     * Should get '500 Internal Server Error' error response when searching with bad id.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldGetInternalServerErrorOnSearchWithBadId() throws Exception {
        // GIVEN
        testDatasetLoader.loadTestDataset();
        final String urlTemplate = "%s/ABCDE".formatted(EMPLOYEES_URL);
        final MockHttpServletRequestBuilder requestBuilder = get(urlTemplate).accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isInternalServerError());
        resultActions.andExpect(jsonPath("message", Matchers.containsString("Failed to convert")));
        logger.info("shouldGetInternalServerErrorOnSearchWithBadId():");
    }

    /**
     * Should find the {@link Employee}s by first name and last name.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldFindEmployeesByFirstNameAndLastName() throws Exception {
        // GIVEN
        final String templateUrl = "%s%s/search/findByFirstNameAndLastNameOrderByLastName".formatted(ROOT_URL, EMPLOYEES_PATH);
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = get(templateUrl)
                .param("firstName", EXPECTED_EMPLOYEE_F_NAME).param("lastName", EXPECTED_EMPLOYEE_L_NAME)
                .accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        checkEmployeeList(templateUrl, resultActions, 1);
        logger.info("shouldFindEmployeesByFirstNameAndLastName():");
    }

    /**
     * Should find {@link Employee}s by first name and last name using patterns.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldFindEmployeesUsingLikePatternByFirstNameAndLastName() throws Exception {
        // GIVEN
        final String templateUrl =
                "%s%s/search/findByFirstNameLikeAndLastNameLikeOrderByLastName".formatted(ROOT_URL, EMPLOYEES_PATH);
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = get(templateUrl).param("firstName", NAME_LIKE)
                .param("lastName", NAME_LIKE).accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        checkEmployeeList(templateUrl, resultActions, 2);
        logger.info("shouldFindEmployeesUsingLikePatternByFirstNameAndLastName():");
    }

    /**
     * Should find the {@link Employee}s by the department's name.
     * <p>
     * Tests a <b>GET</b> request.
     * </p>
     *
     * @throws Exception the {@link Exception}
     */
    @Test
    void shouldFindEmployeesByDepartmentName() throws Exception {
        // GIVEN
        final String templateUrl =
                "%s%s/search/findByDepartmentNameOrderByLastNameDesc".formatted(ROOT_URL, EMPLOYEES_PATH);
        testDatasetLoader.loadTestDataset();
        final MockHttpServletRequestBuilder requestBuilder = get(templateUrl)
                .param("name", EXPECTED_DEPARTMENT_NAME).accept(MediaTypes.HAL_JSON_VALUE);
        // WHEN
        final ResultActions resultActions = mockMvc.perform(requestBuilder);
        // THEN
        if (VERBOSE) {
            resultActions.andDo(print());
        }
        resultActions.andExpect(status().isOk());
        resultActions.andExpect(content().contentType(MediaTypes.HAL_JSON_VALUE));
        resultActions.andExpect(jsonPath("_embedded.employees").isArray());
        resultActions.andExpect(jsonPath("_embedded.employees", Matchers.hasSize(2)));
        // checking last item in list
        resultActions.andExpect(jsonPath("_embedded.employees[1].firstName").value(EXPECTED_EMPLOYEE_F_NAME));
        resultActions.andExpect(jsonPath("_embedded.employees[1].lastName").value(EXPECTED_EMPLOYEE_L_NAME));
        resultActions.andExpect(jsonPath("_embedded.employees[1]._links.self.href")
                .value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_embedded.employees[1]._links.employee.href")
                .value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_embedded.employees[1]._links.department.href")
                .value(EXPECTED_EMPLOYEE_ID_DEP_HREF));
        resultActions.andExpect(jsonPath("_links.self.href").value(templateUrl));
        logger.info("shouldFindEmployeesByDepartmentName():");
    }

    /**
     * Checks the {@link Employee}
     *
     * @param resultActions             the {@link ResultActions}
     * @param expectedEmployeeFirstName the expected {@link Employee}'s first name
     * @param expectedEmployeeLastName  the expected {@link Employee}'s last name
     * @throws Exception the {@link Exception}
     */
    private void checkEmployee(ResultActions resultActions, String expectedEmployeeFirstName,
                               String expectedEmployeeLastName) throws Exception {

        resultActions.andExpect(jsonPath("firstName").value(expectedEmployeeFirstName));
        resultActions.andExpect(jsonPath("lastName").value(expectedEmployeeLastName));
        resultActions.andExpect(jsonPath("_links.self.href").value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_links.employee.href").value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_links.department.href").value(EXPECTED_EMPLOYEE_ID_DEP_HREF));
    }

    /**
     * Checks the list of the {@link Employee}s
     *
     * @param templateUrl   the template URL
     * @param resultActions the {@link ResultActions}
     * @param listSize      the expected size of the list
     * @throws Exception the {@link Exception}
     */
    private void checkEmployeeList(String templateUrl, ResultActions resultActions, int listSize) throws Exception {

        resultActions.andExpect(jsonPath("_embedded.employees").isArray());
        resultActions.andExpect(jsonPath("_embedded.employees", Matchers.hasSize(listSize)));
        resultActions.andExpect(jsonPath("_embedded.employees[0].firstName").value(EXPECTED_EMPLOYEE_F_NAME));
        resultActions.andExpect(jsonPath("_embedded.employees[0].lastName").value(EXPECTED_EMPLOYEE_L_NAME));
        resultActions.andExpect(jsonPath("_embedded.employees[0]._links.self.href")
                .value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_embedded.employees[0]._links.employee.href")
                .value(EXPECTED_EMPLOYEE_ID_URL));
        resultActions.andExpect(jsonPath("_embedded.employees[0]._links.department.href")
                .value(EXPECTED_EMPLOYEE_ID_DEP_HREF));
        resultActions.andExpect(jsonPath("_links.self.href").value(templateUrl));
    }
}
